In [1]:
# !pip install earthengine-api

In [6]:
import ee
import pandas as pd
import os

In [7]:
ee.Initialize()

In [8]:
district = 'jaunpur'
tehsil = 'badlapur'

In [9]:
# def return_all_specified_layers(
#         block_name = ,
#         layer_type = ,
#         layer_name = '',
#         generated_after = '2025-08-05'
# )

List all assets of a specified block

In [10]:
folder_path = 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur'

In [11]:
assets_in_folder = ee.data.listAssets({'parent': folder_path})
assets_in_folder

{'assets': [{'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_annual_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_annual_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:44:36.414561Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:45:52.377595Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur_2017_2022',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur_2017_2022',
   'updateTime': '2025-06-17T11:42:03.637451Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur_2022_2024',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur_2022_2024',
   'updateTime': '2025-06-17T11:43:00.428786Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Prec_annual_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Prec_annual_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:50:35.426392Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Prec_fortnight_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Prec_fortnight_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:53:31.437276Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Runoff_annual_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Runoff_annual_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:06:08.557616Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Runoff_fortnight_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Runoff_fortnight_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:27:01.910022Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/admin_boundary_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/admin_boundary_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:29:19.105074Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/aquifer_vector_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/aquifer_vector_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:26:12.691700Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Afforestation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Afforestation',
   'updateTime': '2025-06-17T13:00:15.965994Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_CropIntensity',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_CropIntensity',
   'updateTime': '2025-06-17T12:59:27.071414Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Deforestation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Deforestation',
   'updateTime': '2025-06-17T12:52:17.575965Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Degradation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Degradation',
   'updateTime': '2025-06-17T12:46:50.922720Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Urbanization',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Urbanization',
   'updateTime': '2025-06-17T12:44:27.782579Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Afforestation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Afforestation',
   'updateTime': '2025-06-18T05:58:58.437510Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_CropIntensity',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_CropIntensity',
   'updateTime': '2025-06-18T06:05:39.106745Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Deforestation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Deforestation',
   'updateTime': '2025-06-18T06:00:04.141443Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Degradation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Degradation',
   'updateTime': '2025-06-18T06:02:24.429832Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Urbanization',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Urbanization',
   'updateTime': '2025-06-18T06:03:56.042132Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/clart_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/clart_jaunpur_badlapur',
   'updateTime': '2025-06-18T06:09:02.031735Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/crop_grid_jaunpur_badlapur_with_uid_16ha',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/crop_grid_jaunpur_badlapur_with_uid_16ha',
   'updateTime': '2025-06-17T12:37:15.167061Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/cropping_intensity_jaunpur_badlapur_2017-23',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/cropping_intensity_jaunpur_badlapur_2017-23',
   'updateTime': '2025-07-02T12:20:27.440406Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drainage_density_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drainage_density_jaunpur_badlapur',
   'updateTime': '2025-06-18T06:06:54.117532Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drainage_lines_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drainage_lines_jaunpur_badlapur',
   'updateTime': '2025-06-17T12:38:20.798842Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drought_jaunpur_badlapur_2017_2022',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drought_jaunpur_badlapur_2017_2022',
   'updateTime': '2025-06-17T13:36:40.094006Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_delta_g_annual_jaunpur_badlapur_uid',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_delta_g_annual_jaunpur_badlapur_uid',
   'updateTime': '2025-06-17T13:25:04.593822Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_delta_g_fortnight_jaunpur_badlapur_uid',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_delta_g_fortnight_jaunpur_badlapur_uid',
   'updateTime': '2025-06-17T13:31:35.505780Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_mws_jaunpur_badlapur_uid',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_mws_jaunpur_badlapur_uid',
   'updateTime': '2025-06-17T11:33:34.629698Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2017-07-01_2018-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2017-07-01_2018-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T11:55:38.344873Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2018-07-01_2019-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2018-07-01_2019-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T11:58:23.395326Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2019-07-01_2020-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2019-07-01_2020-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:01:51.621461Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2020-07-01_2021-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2020-07-01_2021-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:03:21.003313Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2021-07-01_2022-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2021-07-01_2022-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:06:47.466825Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2022-07-01_2023-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2022-07-01_2023-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:08:03.260112Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2023-07-01_2024-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2023-07-01_2024-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:09:38.445308Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_lulcXplains_clusters',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_lulcXplains_clusters',
   'updateTime': '2025-06-18T06:07:44.988027Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_terrain_clusters',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_terrain_clusters',
   'updateTime': '2025-06-17T13:06:58.042973Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/lulc_vector_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/lulc_vector_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:26:00.971278Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/restoration_jaunpur_badlapur_raster',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/restoration_jaunpur_badlapur_raster',
   'updateTime': '2025-06-17T13:23:53.257516Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/restoration_jaunpur_badlapur_vector',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/restoration_jaunpur_badlapur_vector',
   'updateTime': '2025-06-17T13:28:30.946981Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/soge_vector_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/soge_vector_jaunpur_badlapur',
   'updateTime': '2025-06-18T06:03:34.490819Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb1_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb1_jaunpur_badlapur',
   'updateTime': '2025-06-17T12:35:45.500774Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb2_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb2_jaunpur_badlapur',
   'updateTime': '2025-06-17T12:38:11.763570Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb3_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb3_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:02:52.576123Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/terrain_raster_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/terrain_raster_jaunpur_badlapur',
   'updateTime': '2025-06-17T12:36:42.613392Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2017',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2017',
   'updateTime': '2025-07-14T07:08:22.814337Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2018',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2018',
   'updateTime': '2025-07-14T07:15:05.642308Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2019',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2019',
   'updateTime': '2025-07-14T07:22:39.246702Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2020',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2020',
   'updateTime': '2025-07-14T07:31:31.954773Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2021',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2021',
   'updateTime': '2025-07-14T07:43:08.241689Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2022',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2022',
   'updateTime': '2025-07-14T07:51:17.722981Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2017',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2017',
   'updateTime': '2025-07-14T11:25:59.002672Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2018',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2018',
   'updateTime': '2025-07-14T11:28:00.262308Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2019',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2019',
   'updateTime': '2025-07-14T11:30:01.242355Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2020',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2020',
   'updateTime': '2025-07-14T11:36:06.504880Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2021',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2021',
   'updateTime': '2025-07-14T11:37:59.971947Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2022',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2022',
   'updateTime': '2025-07-14T11:40:24.529079Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2017',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2017',
   'updateTime': '2025-07-14T07:09:35.815896Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2018',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2018',
   'updateTime': '2025-07-14T07:16:41.749671Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2019',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2019',
   'updateTime': '2025-07-14T07:22:24.592839Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2020',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2020',
   'updateTime': '2025-07-14T07:28:49.055396Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2021',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2021',

In [12]:
block_layers_df = pd.DataFrame.from_dict(assets_in_folder['assets'])

In [13]:
block_layers_df.head()

,type,name,id,updateTime
0,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:44:36.414561Z
1,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:45:52.377595Z
2,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:42:03.637451Z
3,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:43:00.428786Z
4,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:50:35.426392Z

In [14]:
block_layers_df.shape

(72, 4)

In [15]:
block_layers_df['type'].value_counts()

type
TABLE    44
IMAGE    28
Name: count, dtype: int64

In [16]:
os.path.basename(block_layers_df['name'][0])

'ET_annual_jaunpur_badlapur'

In [17]:
all(block_layers_df['name'] == block_layers_df['id'])

True

In [18]:
block_layers_df.drop('id',axis=1,inplace=True)

In [19]:
block_layers_df['base_name'] = block_layers_df['name'].apply(os.path.basename)

In [20]:
block_layers_df

,type,name,updateTime,base_name
0,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:44:36.414561Z,ET_annual_jaunpur_badlapur
1,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:45:52.377595Z,ET_fortnight_jaunpur_badlapur
2,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:42:03.637451Z,ET_fortnight_jaunpur_badlapur_2017_2022
3,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:43:00.428786Z,ET_fortnight_jaunpur_badlapur_2022_2024
4,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:50:35.426392Z,Prec_annual_jaunpur_badlapur
...,...,...,...,...
67,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-07-14T11:37:25.100914Z,tree_health_ch_vector_jaunpur_badlapur_2021
68,IMAGE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T13:02:59.200008Z,tree_health_overall_change_raster_jaunpur_badl...
69,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-18T05:58:32.651328Z,tree_health_overall_change_vector_jaunpur_badl...
70,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T13:27:50.184409Z,well_depth_annual_jaunpur_badlapur
71,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T13:29:48.351576Z,well_depth_net_value_jaunpur_badlapur

In [21]:
def extract_layer_name(base_name,
                       district_name = district,
                       tehsil_name = tehsil):
    layer_name = base_name.split('_')
    layer_name.remove(district_name)
    layer_name.remove(tehsil_name)
    layer_name = '_'.join(layer_name)
    return layer_name

In [22]:
block_layers_df['layer_name'] = block_layers_df['base_name'].apply(extract_layer_name)

In [23]:
block_layers_df[['type','name','base_name','layer_name']]

,type,name,base_name,layer_name
0,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,ET_annual_jaunpur_badlapur,ET_annual
1,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,ET_fortnight_jaunpur_badlapur,ET_fortnight
2,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,ET_fortnight_jaunpur_badlapur_2017_2022,ET_fortnight_2017_2022
3,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,ET_fortnight_jaunpur_badlapur_2022_2024,ET_fortnight_2022_2024
4,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,Prec_annual_jaunpur_badlapur,Prec_annual
...,...,...,...,...
67,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,tree_health_ch_vector_jaunpur_badlapur_2021,tree_health_ch_vector_2021
68,IMAGE,projects/ee-corestackdev/assets/apps/mws/uttar...,tree_health_overall_change_raster_jaunpur_badl...,tree_health_overall_change_raster
69,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,tree_health_overall_change_vector_jaunpur_badl...,tree_health_overall_change_vector
70,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,well_depth_annual_jaunpur_badlapur,well_depth_annual
71,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,well_depth_net_value_jaunpur_badlapur,well_depth_net_value

In [24]:
block_layers_df[['type','layer_name']]

     type                         layer_name
0   TABLE                          ET_annual
1   TABLE                       ET_fortnight
2   TABLE             ET_fortnight_2017_2022
3   TABLE             ET_fortnight_2022_2024
4   TABLE                        Prec_annual
..    ...                                ...
67  TABLE         tree_health_ch_vector_2021
68  IMAGE  tree_health_overall_change_raster
69  TABLE  tree_health_overall_change_vector
70  TABLE                  well_depth_annual
71  TABLE               well_depth_net_value

[72 rows x 2 columns]

### Extract column names for each vector layers

In [25]:
block_layers_df['type'].iloc[0]

'TABLE'

In [26]:
vector_layers_df = block_layers_df[block_layers_df['type'] == 'TABLE']

In [27]:
vector_layers_df['layer_name']

0                             ET_annual
1                          ET_fortnight
2                ET_fortnight_2017_2022
3                ET_fortnight_2022_2024
4                           Prec_annual
5                        Prec_fortnight
6                         Runoff_annual
7                      Runoff_fortnight
8                        admin_boundary
9                        aquifer_vector
15          change_vector_Afforestation
16          change_vector_CropIntensity
17          change_vector_Deforestation
18            change_vector_Degradation
19           change_vector_Urbanization
21              crop_grid_with_uid_16ha
22           cropping_intensity_2017-23
24                       drainage_lines
25                    drought_2017_2022
26          filtered_delta_g_annual_uid
27       filtered_delta_g_fortnight_uid
28                     filtered_mws_uid
36                 lulcXplains_clusters
37                     terrain_clusters
38                          lulc_vector
40                   restoration_vector
41                          soge_vector
42                                 swb1
43                                 swb2
44                                 swb3
52          tree_health_ccd_vector_2017
53          tree_health_ccd_vector_2018
54          tree_health_ccd_vector_2019
55          tree_health_ccd_vector_2020
56          tree_health_ccd_vector_2021
57          tree_health_ccd_vector_2022
63           tree_health_ch_vector_2017
64           tree_health_ch_vector_2018
65           tree_health_ch_vector_2019
66           tree_health_ch_vector_2020
67           tree_health_ch_vector_2021
69    tree_health_overall_change_vector
70                    well_depth_annual
71                 well_depth_net_value
Name: layer_name, dtype: object

In [31]:
# test = ee.FeatureCollection(vector_layers_df['name'].iloc[0])

In [32]:
# test.first().propertyNames().getInfo()

In [28]:
def extract_column_names(layer_path):
    layer_columns = ee.FeatureCollection(layer_path)
    layer_columns = layer_columns.first().propertyNames().getInfo()
    return layer_columns

In [29]:
vector_layers_df['column_names'] = vector_layers_df['name'].apply(extract_column_names)

/tmp/ipykernel_15366/4124125797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vector_layers_df['column_names'] = vector_layers_df['name'].apply(extract_column_names)

In [30]:
vector_layers_df[['layer_name','column_names']]

,layer_name,column_names
0,ET_annual,"[2019-07-01, uid, 2018-07-01, 2023-07-01, 2021..."
1,ET_fortnight,"[2020-02-24, 2020-05-18, 2020-11-18, 2024-01-1..."
2,ET_fortnight_2017_2022,"[2020-02-24, 2020-05-18, 2020-11-18, 2019-04-2..."
3,ET_fortnight_2022_2024,"[2024-01-13, 2024-04-06, 2024-05-18, 2024-02-2..."
4,Prec_annual,"[2019-07-01, uid, 2018-07-01, 2023-07-01, 2021..."
5,Prec_fortnight,"[2020-02-24, 2020-05-18, 2020-11-18, 2024-01-1..."
6,Runoff_annual,"[2019-07-01, uid, 2018-07-01, 2023-07-01, 2021..."
7,Runoff_fortnight,"[2020-02-24, 2020-05-18, 2020-11-18, 2024-01-1..."
8,admin_boundary,"[ASSET_2001, TOT_M, dist_cen, TOT_F, ADI_2019,..."
9,aquifer_vector,"[weighted_contribution, aquifer_count, m2_perd..."
15,change_vector_Afforestation,"[uid, area_in_ha, fa_fo, total_aff, sc_fo, ba_..."
16,change_vector_CropIntensity,"[tr_si, si_do, uid, si_tr, same, area_in_ha, d..."
17,change_vector_Deforestation,"[fo_fa, uid, fo_ba, total_def, area_in_ha, fo_..."
18,change_vector_Degradation,"[uid, f_bu, f_sc, area_in_ha, total_deg, f_ba,..."
19,change_vector_Urbanization,"[uid, tr_bu, bu_bu, total_urb, area_in_ha, id,..."
21,crop_grid_with_uid_16ha,"[uid, system:index]"
22,cropping_intensity_2017-23,"[single_cropped_area_2018, total_cropable_area..."
24,drainage_lines,"[end_node, ORDER, stream_typ, start_node, cat,..."
25,drought_2017_2022,"[rd21-6-26, rd20-9-4, rd17-6-4, rd18-6-20, rd2..."
26,filtered_delta_g_annual_uid,"[uid, 2022_2023, 2017_2018, area_in_ha, 2023_2..."
27,filtered_delta_g_fortnight_uid,"[2020-05-18, 2020-02-24, 2020-11-18, 2024-04-0..."
28,filtered_mws_uid,"[uid, id, area_in_ha, system:index]"
36,lulcXplains_clusters,"[LxP_cluster, area, clust_name, forest, shrubs..."
37,terrain_clusters,"[hill_slopes_area, uid, slopy_area, area_in_ha..."
38,lulc_vector,"[single_kharif_cropped_area_2019, single_khari..."
40,restoration_vector,"[uid, area_in_ha, Excluded Areas, id, Mosaic R..."
41,soge_vector,"[code, soge_block, agwd_dom_i, pct_area_soge, ..."
42,swb1,"[kr_20-21, krz_18-19, area_21-22, area_23-24, ..."
43,swb2,"[kr_20-21, krz_18-19, area_21-22, area_23-24, ..."
44,swb3,"[no_town_cities_benefited, area_21-22, census_..."
52,tree_health_ccd_vector_2017,"[uid, lo_de_2017, hi_de_2017, area_in_ha, sum,..."
53,tree_health_ccd_vector_2018,"[uid, hi_de_2018, lo_de_2018, area_in_ha, mi_d..."
54,tree_health_ccd_vector_2019,"[uid, area_in_ha, hi_de_2019, mi_da_2019, lo_d..."
55,tree_health_ccd_vector_2020,"[uid, mi_da_2020, area_in_ha, sum, id, lo_de_2..."
56,tree_health_ccd_vector_2021,"[mi_da_2021, uid, area_in_ha, sum, id, hi_de_2..."
57,tree_health_ccd_vector_2022,"[mi_da_2022, uid, lo_de_2022, area_in_ha, sum,..."
63,tree_health_ch_vector_2017,"[md_tr_2017, uid, sh_tr_2017, area_in_ha, sum,..."
64,tree_health_ch_vector_2018,"[uid, md_tr_2018, sh_tr_2018, area_in_ha, mi_d..."
65,tree_health_ch_vector_2019,"[uid, md_tr_2019, tl_tr_2019, sh_tr_2019, area..."
66,tree_health_ch_vector_2020,"[uid, tl_tr_2020, mi_da_2020, area_in_ha, md_t..."
67,tree_health_ch_vector_2021,"[mi_da_2021, uid, tl_tr_2021, area_in_ha, sum,..."
69,tree_health_overall_change_vector,"[Degradation, Deforestation, uid, Improvement,..."
70,well_depth_annual,"[uid, 2022_2023, 2017_2018, weighted_avg_yeild..."
71,well_depth_net_value,"[weighted_avg_yeild, 2023_2024, Net2019_24, Ne..."

In [37]:
len(list_of_vector_layer)

44

In [39]:
vector_layers_df['layer_name'].to_list()

['ET_annual',
 'ET_fortnight',
 'ET_fortnight_2017_2022',
 'ET_fortnight_2022_2024',
 'Prec_annual',
 'Prec_fortnight',
 'Runoff_annual',
 'Runoff_fortnight',
 'admin_boundary',
 'aquifer_vector',
 'change_vector_Afforestation',
 'change_vector_CropIntensity',
 'change_vector_Deforestation',
 'change_vector_Degradation',
 'change_vector_Urbanization',
 'crop_grid_with_uid_16ha',
 'cropping_intensity_2017-23',
 'drainage_lines',
 'drought_2017_2022',
 'filtered_delta_g_annual_uid',
 'filtered_delta_g_fortnight_uid',
 'filtered_mws_uid',
 'lulcXplains_clusters',
 'terrain_clusters',
 'lulc_vector',
 'restoration_vector',
 'soge_vector',
 'swb1',
 'swb2',
 'swb3',
 'tree_health_ccd_vector_2017',
 'tree_health_ccd_vector_2018',
 'tree_health_ccd_vector_2019',
 'tree_health_ccd_vector_2020',
 'tree_health_ccd_vector_2021',
 'tree_health_ccd_vector_2022',
 'tree_health_ch_vector_2017',
 'tree_health_ch_vector_2018',
 'tree_health_ch_vector_2019',
 'tree_health_ch_vector_2020',
 'tree_health_ch_vector_2021',
 'tree_health_overall_change_vector',
 'well_depth_annual',
 'well_depth_net_value']

In [40]:
row_index_new = [
    'admin_boundary',
    'aquifer_vector',
    'drainage_lines',
    'swb3',#level1
    'change_vector_Afforestation',
    'change_vector_CropIntensity',
    'change_vector_Deforestation',
    'change_vector_Degradation',
    'change_vector_Urbanization',
    'cropping_intensity_2017-23',
    'drought_2017_2022', 
    'restoration_vector',
    'soge_vector', #level2
    'lulc_vector',
    'lulcXplains_clusters',
    'terrain_clusters',
    'tree_health_ccd_vector_2017',
    'tree_health_overall_change_vector', #level3
    'ET_annual',
    'ET_fortnight',
    'Runoff_annual',
    'Runoff_fortnight',
    'Prec_annual',
    'Prec_fortnight',
    'filtered_delta_g_annual_uid',
    'filtered_delta_g_fortnight_uid',
    'well_depth_annual',
    'well_depth_net_value' #level4
]

In [ ]:
row_indices = []
for layername in row_index_new:
    row_indices.append(vector_layers_df[vector_layers_df['layer_name'] == layername].index.array)

In [89]:
row_indices = [int(x) for y in row_indices for x in y]

In [135]:
vector_layers_filtered_df = vector_layers_df.reindex(row_indices)

In [136]:
vector_layers_filtered_df.columns

Index(['type', 'name', 'updateTime', 'base_name', 'layer_name',
       'column_names'],
      dtype='object')

In [137]:
vector_layers_filtered_df = vector_layers_filtered_df[['layer_name','column_names']].explode('column_names') 
#https://stackoverflow.com/questions/42012152/unstack-a-pandas-column-containing-lists-into-multiple-rows

In [138]:
vector_layers_filtered_df['column_name_normalized'] = ''

In [139]:
vector_layers_filtered_df['column_name_description'] = ''

In [140]:
vector_layers_filtered_df.rename(columns={'column_names' : 'column_name'},inplace=True)

In [141]:
vector_layers_filtered_df

,layer_name,column_name,column_name_normalized,column_name_description
8,admin_boundary,ASSET_2001,,
8,admin_boundary,TOT_M,,
8,admin_boundary,dist_cen,,
8,admin_boundary,TOT_F,,
8,admin_boundary,ADI_2019,,
...,...,...,...,...
71,well_depth_net_value,2017_2018,,
71,well_depth_net_value,area_in_ha,,
71,well_depth_net_value,id,,
71,well_depth_net_value,2021_2022,,
71,well_depth_net_value,system:index,,

In [143]:
vector_layers_filtered_df.reset_index(drop=True,inplace=True)

In [144]:
# vector_layers_filtered_df

In [145]:
vector_layers_filtered_df.to_csv('../data/vector_columns_filtered.csv')

In [54]:
vector_layers_df[vector_layers_df['layer_name'] == 'admin_boundary']['column_names'].iloc[0]

['ASSET_2001',
 'TOT_M',
 'dist_cen',
 'TOT_F',
 'ADI_2019',
 'F_SC',
 'P_ILL',
 'MSW_2011',
 'TOT_P',
 'ADI_2011',
 'MSW_2019',
 'P_ST',
 'F_ILL',
 'vill_name',
 'vill_ID',
 'BF_2011',
 'FC_2001',
 'F_ST',
 'P_LIT',
 'state',
 'block_cen',
 'ADI_2001',
 'BF_2019',
 'No_HH',
 'ASSET_2011',
 'M_SC',
 'MSW_2001',
 'M_LIT',
 'tehsil',
 'state_cen',
 'FC_2019',
 'M_ST',
 'district',
 'F_LIT',
 'BF_2001',
 'P_SC',
 'ASSET_2019',
 'FC_2011',
 'M_ILL',
 'system:index']

### Admin boundary layer

In [67]:
admin_boundary_df = \
    ee.data.listFeatures({
    'assetId' : vector_layers_df[vector_layers_df['layer_name'] == 'admin_boundary']['name'].iloc[0],
    'fileFormat' : 'PANDAS_DATAFRAME'
    })

In [69]:
admin_boundary_df.columns

Index(['geo', 'ADI_2001', 'ADI_2011', 'ADI_2019', 'ASSET_2001', 'ASSET_2011',
       'ASSET_2019', 'BF_2001', 'BF_2011', 'BF_2019', 'FC_2001', 'FC_2011',
       'FC_2019', 'F_ILL', 'F_LIT', 'F_SC', 'F_ST', 'MSW_2001', 'MSW_2011',
       'MSW_2019', 'M_ILL', 'M_LIT', 'M_SC', 'M_ST', 'No_HH', 'P_ILL', 'P_LIT',
       'P_SC', 'P_ST', 'TOT_F', 'TOT_M', 'TOT_P', 'block_cen', 'dist_cen',
       'district', 'state', 'state_cen', 'tehsil', 'vill_ID', 'vill_name'],
      dtype='object')

In [71]:
admin_boundary_df.shape

(458, 40)

In [70]:
admin_boundary_df.describe()

,ADI_2001,ADI_2011,ADI_2019,ASSET_2001,ASSET_2011,ASSET_2019,BF_2011,BF_2019,FC_2001,FC_2011,...,P_LIT,P_SC,P_ST,TOT_F,TOT_M,TOT_P,block_cen,dist_cen,state_cen,vill_ID
count,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,...,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000,458.000000
mean,6.026201,6.360262,6.351528,1.406114,1.401747,1.401747,0.700873,0.700873,1.028384,1.240175,...,715.556769,245.382096,0.751092,590.423581,573.897380,1164.320961,969.270742,191.458515,8.882096,198210.565502
std,3.999367,4.209907,4.191897,0.924340,0.916752,0.916752,0.458376,0.458376,0.898127,0.998446,...,720.765914,267.626140,11.209720,585.447873,583.049705,1167.239658,111.797179,22.082881,1.024464,22862.760023
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,266.750000,57.000000,0.000000,230.250000,220.250000,447.500000,982.000000,194.000000,9.000000,200688.250000
50%,8.000000,9.000000,9.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,550.500000,178.000000,0.000000,464.000000,444.000000,906.000000,982.000000,194.000000,9.000000,200803.500000
75%,9.000000,9.000000,9.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,2.000000,...,882.750000,342.500000,0.000000,745.000000,719.750000,1450.000000,982.000000,194.000000,9.000000,200918.750000
max,13.000000,11.000000,11.000000,3.000000,2.000000,2.000000,1.000000,1.000000,3.000000,3.000000,...,6920.000000,1849.000000,236.000000,5709.000000,5813.000000,11522.000000,984.000000,194.000000,9.000000,201837.000000