In [ ]:
# !pip install earthengine-api

In [1]:
import ee
import pandas as pd
import os

In [2]:
ee.Initialize()

In [3]:
district = 'jaunpur'
tehsil = 'badlapur'

List all assets of a specified block

In [4]:
folder_path = 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur'

In [5]:
assets_in_folder = ee.data.listAssets({'parent': folder_path})
assets_in_folder

{'assets': [{'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_annual_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_annual_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:44:36.414561Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:45:52.377595Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur_2017_2022',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur_2017_2022',
   'updateTime': '2025-06-17T11:42:03.637451Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur_2022_2024',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/ET_fortnight_jaunpur_badlapur_2022_2024',
   'updateTime': '2025-06-17T11:43:00.428786Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Prec_annual_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Prec_annual_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:50:35.426392Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Prec_fortnight_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Prec_fortnight_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:53:31.437276Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Runoff_annual_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Runoff_annual_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:06:08.557616Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Runoff_fortnight_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/Runoff_fortnight_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:27:01.910022Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/admin_boundary_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/admin_boundary_jaunpur_badlapur',
   'updateTime': '2025-06-17T11:29:19.105074Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/aquifer_vector_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/aquifer_vector_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:26:12.691700Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Afforestation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Afforestation',
   'updateTime': '2025-06-17T13:00:15.965994Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_CropIntensity',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_CropIntensity',
   'updateTime': '2025-06-17T12:59:27.071414Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Deforestation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Deforestation',
   'updateTime': '2025-06-17T12:52:17.575965Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Degradation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Degradation',
   'updateTime': '2025-06-17T12:46:50.922720Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Urbanization',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_jaunpur_badlapur_Urbanization',
   'updateTime': '2025-06-17T12:44:27.782579Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Afforestation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Afforestation',
   'updateTime': '2025-06-18T05:58:58.437510Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_CropIntensity',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_CropIntensity',
   'updateTime': '2025-06-18T06:05:39.106745Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Deforestation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Deforestation',
   'updateTime': '2025-06-18T06:00:04.141443Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Degradation',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Degradation',
   'updateTime': '2025-06-18T06:02:24.429832Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Urbanization',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/change_vector_jaunpur_badlapur_Urbanization',
   'updateTime': '2025-06-18T06:03:56.042132Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/clart_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/clart_jaunpur_badlapur',
   'updateTime': '2025-06-18T06:09:02.031735Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/crop_grid_jaunpur_badlapur_with_uid_16ha',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/crop_grid_jaunpur_badlapur_with_uid_16ha',
   'updateTime': '2025-06-17T12:37:15.167061Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/cropping_intensity_jaunpur_badlapur_2017-23',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/cropping_intensity_jaunpur_badlapur_2017-23',
   'updateTime': '2025-07-02T12:20:27.440406Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drainage_density_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drainage_density_jaunpur_badlapur',
   'updateTime': '2025-06-18T06:06:54.117532Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drainage_lines_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drainage_lines_jaunpur_badlapur',
   'updateTime': '2025-06-17T12:38:20.798842Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drought_jaunpur_badlapur_2017_2022',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/drought_jaunpur_badlapur_2017_2022',
   'updateTime': '2025-06-17T13:36:40.094006Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_delta_g_annual_jaunpur_badlapur_uid',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_delta_g_annual_jaunpur_badlapur_uid',
   'updateTime': '2025-06-17T13:25:04.593822Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_delta_g_fortnight_jaunpur_badlapur_uid',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_delta_g_fortnight_jaunpur_badlapur_uid',
   'updateTime': '2025-06-17T13:31:35.505780Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_mws_jaunpur_badlapur_uid',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/filtered_mws_jaunpur_badlapur_uid',
   'updateTime': '2025-06-17T11:33:34.629698Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2017-07-01_2018-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2017-07-01_2018-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T11:55:38.344873Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2018-07-01_2019-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2018-07-01_2019-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T11:58:23.395326Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2019-07-01_2020-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2019-07-01_2020-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:01:51.621461Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2020-07-01_2021-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2020-07-01_2021-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:03:21.003313Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2021-07-01_2022-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2021-07-01_2022-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:06:47.466825Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2022-07-01_2023-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2022-07-01_2023-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:08:03.260112Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2023-07-01_2024-06-30_LULCmap_10m',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_2023-07-01_2024-06-30_LULCmap_10m',
   'updateTime': '2025-06-17T12:09:38.445308Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_lulcXplains_clusters',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_lulcXplains_clusters',
   'updateTime': '2025-06-18T06:07:44.988027Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_terrain_clusters',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/jaunpur_badlapur_terrain_clusters',
   'updateTime': '2025-06-17T13:06:58.042973Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/lulc_vector_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/lulc_vector_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:26:00.971278Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/restoration_jaunpur_badlapur_raster',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/restoration_jaunpur_badlapur_raster',
   'updateTime': '2025-06-17T13:23:53.257516Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/restoration_jaunpur_badlapur_vector',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/restoration_jaunpur_badlapur_vector',
   'updateTime': '2025-06-17T13:28:30.946981Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/soge_vector_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/soge_vector_jaunpur_badlapur',
   'updateTime': '2025-06-18T06:03:34.490819Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb1_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb1_jaunpur_badlapur',
   'updateTime': '2025-06-17T12:35:45.500774Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb2_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb2_jaunpur_badlapur',
   'updateTime': '2025-06-17T12:38:11.763570Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb3_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/swb3_jaunpur_badlapur',
   'updateTime': '2025-06-17T13:02:52.576123Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/terrain_raster_jaunpur_badlapur',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/terrain_raster_jaunpur_badlapur',
   'updateTime': '2025-06-17T12:36:42.613392Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2017',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2017',
   'updateTime': '2025-07-14T07:08:22.814337Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2018',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2018',
   'updateTime': '2025-07-14T07:15:05.642308Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2019',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2019',
   'updateTime': '2025-07-14T07:22:39.246702Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2020',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2020',
   'updateTime': '2025-07-14T07:31:31.954773Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2021',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2021',
   'updateTime': '2025-07-14T07:43:08.241689Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2022',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_raster_jaunpur_badlapur_2022',
   'updateTime': '2025-07-14T07:51:17.722981Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2017',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2017',
   'updateTime': '2025-07-14T11:25:59.002672Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2018',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2018',
   'updateTime': '2025-07-14T11:28:00.262308Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2019',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2019',
   'updateTime': '2025-07-14T11:30:01.242355Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2020',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2020',
   'updateTime': '2025-07-14T11:36:06.504880Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2021',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2021',
   'updateTime': '2025-07-14T11:37:59.971947Z'},
  {'type': 'TABLE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2022',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ccd_vector_jaunpur_badlapur_2022',
   'updateTime': '2025-07-14T11:40:24.529079Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2017',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2017',
   'updateTime': '2025-07-14T07:09:35.815896Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2018',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2018',
   'updateTime': '2025-07-14T07:16:41.749671Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2019',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2019',
   'updateTime': '2025-07-14T07:22:24.592839Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2020',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2020',
   'updateTime': '2025-07-14T07:28:49.055396Z'},
  {'type': 'IMAGE',
   'name': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2021',
   'id': 'projects/ee-corestackdev/assets/apps/mws/uttar_pradesh/jaunpur/badlapur/tree_health_ch_raster_jaunpur_badlapur_2021',

In [6]:
block_layers_df = pd.DataFrame.from_dict(assets_in_folder['assets'])

In [7]:
block_layers_df.head()

,type,name,id,updateTime
0,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:44:36.414561Z
1,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:45:52.377595Z
2,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:42:03.637451Z
3,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:43:00.428786Z
4,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:50:35.426392Z

In [8]:
block_layers_df['type'].value_counts()

type
TABLE    44
IMAGE    28
Name: count, dtype: int64

In [9]:
os.path.basename(block_layers_df['name'][0])

'ET_annual_jaunpur_badlapur'

In [10]:
all(block_layers_df['name'] == block_layers_df['id'])

True

In [11]:
block_layers_df.drop('id',axis=1,inplace=True)

In [12]:
block_layers_df['base_name'] = block_layers_df['name'].apply(os.path.basename)

In [13]:
block_layers_df

,type,name,updateTime,base_name
0,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:44:36.414561Z,ET_annual_jaunpur_badlapur
1,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:45:52.377595Z,ET_fortnight_jaunpur_badlapur
2,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:42:03.637451Z,ET_fortnight_jaunpur_badlapur_2017_2022
3,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:43:00.428786Z,ET_fortnight_jaunpur_badlapur_2022_2024
4,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T11:50:35.426392Z,Prec_annual_jaunpur_badlapur
...,...,...,...,...
67,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-07-14T11:37:25.100914Z,tree_health_ch_vector_jaunpur_badlapur_2021
68,IMAGE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T13:02:59.200008Z,tree_health_overall_change_raster_jaunpur_badl...
69,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-18T05:58:32.651328Z,tree_health_overall_change_vector_jaunpur_badl...
70,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T13:27:50.184409Z,well_depth_annual_jaunpur_badlapur
71,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,2025-06-17T13:29:48.351576Z,well_depth_net_value_jaunpur_badlapur

In [14]:
def extract_layer_name(base_name,
                       district_name = district,
                       tehsil_name = tehsil):
    layer_name = base_name.split('_')
    layer_name.remove(district_name)
    layer_name.remove(tehsil_name)
    layer_name = '_'.join(layer_name)
    return layer_name

In [15]:
block_layers_df['layer_name'] = block_layers_df['base_name'].apply(extract_layer_name)

In [16]:
block_layers_df[['type','name','base_name','layer_name']]

,type,name,base_name,layer_name
0,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,ET_annual_jaunpur_badlapur,ET_annual
1,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,ET_fortnight_jaunpur_badlapur,ET_fortnight
2,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,ET_fortnight_jaunpur_badlapur_2017_2022,ET_fortnight_2017_2022
3,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,ET_fortnight_jaunpur_badlapur_2022_2024,ET_fortnight_2022_2024
4,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,Prec_annual_jaunpur_badlapur,Prec_annual
...,...,...,...,...
67,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,tree_health_ch_vector_jaunpur_badlapur_2021,tree_health_ch_vector_2021
68,IMAGE,projects/ee-corestackdev/assets/apps/mws/uttar...,tree_health_overall_change_raster_jaunpur_badl...,tree_health_overall_change_raster
69,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,tree_health_overall_change_vector_jaunpur_badl...,tree_health_overall_change_vector
70,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,well_depth_annual_jaunpur_badlapur,well_depth_annual
71,TABLE,projects/ee-corestackdev/assets/apps/mws/uttar...,well_depth_net_value_jaunpur_badlapur,well_depth_net_value

In [17]:
block_layers_df[['type','layer_name']]

     type                         layer_name
0   TABLE                          ET_annual
1   TABLE                       ET_fortnight
2   TABLE             ET_fortnight_2017_2022
3   TABLE             ET_fortnight_2022_2024
4   TABLE                        Prec_annual
..    ...                                ...
67  TABLE         tree_health_ch_vector_2021
68  IMAGE  tree_health_overall_change_raster
69  TABLE  tree_health_overall_change_vector
70  TABLE                  well_depth_annual
71  TABLE               well_depth_net_value

[72 rows x 2 columns]

### Extract column names for each vector layers

In [18]:
block_layers_df['type'].iloc[0]

'TABLE'

In [19]:
vector_layers_df = block_layers_df[block_layers_df['type'] == 'TABLE']

In [21]:
vector_layers_df['layer_name']

0                             ET_annual
1                          ET_fortnight
2                ET_fortnight_2017_2022
3                ET_fortnight_2022_2024
4                           Prec_annual
5                        Prec_fortnight
6                         Runoff_annual
7                      Runoff_fortnight
8                        admin_boundary
9                        aquifer_vector
15          change_vector_Afforestation
16          change_vector_CropIntensity
17          change_vector_Deforestation
18            change_vector_Degradation
19           change_vector_Urbanization
21              crop_grid_with_uid_16ha
22           cropping_intensity_2017-23
24                       drainage_lines
25                    drought_2017_2022
26          filtered_delta_g_annual_uid
27       filtered_delta_g_fortnight_uid
28                     filtered_mws_uid
36                 lulcXplains_clusters
37                     terrain_clusters
38                          lulc_vector
40                   restoration_vector
41                          soge_vector
42                                 swb1
43                                 swb2
44                                 swb3
52          tree_health_ccd_vector_2017
53          tree_health_ccd_vector_2018
54          tree_health_ccd_vector_2019
55          tree_health_ccd_vector_2020
56          tree_health_ccd_vector_2021
57          tree_health_ccd_vector_2022
63           tree_health_ch_vector_2017
64           tree_health_ch_vector_2018
65           tree_health_ch_vector_2019
66           tree_health_ch_vector_2020
67           tree_health_ch_vector_2021
69    tree_health_overall_change_vector
70                    well_depth_annual
71                 well_depth_net_value
Name: layer_name, dtype: object